export default {
  _id: '52566848',
  name: 'Handmade Soft Computer',
  reviews: [
    {
      _id: '68730078',
      date: '2017-01-02T08:52:36.408Z',
      username: 'Grady Crona',
      userReviews: 20,
      foodScore: 3,
      serviceScore: 5,
      ambianceScore: 5,
      valueScore: 4,
      overallScore: 5,
      noiseLevel: 3,
      wouldRecommend: true,
      occasion: 'Business Meal',
      recommendedFor: ['Great Beer'],
      review:
        'Accusamus in quo et in. Possimus fugit nobis aut. Ullam aut dolorem perspiciatis perspiciatis quia nostrum.',
    },
    {
      _id: '34823729',
      date: '2018-03-07T05:34:35.466Z',
      username: 'Shannon Stoltenberg III',
      userReviews: 10,
      foodScore: 1,
      serviceScore: 5,
      ambianceScore: 3,
      valueScore: 5,
      overallScore: 4,
      noiseLevel: 3,
      wouldRecommend: true,
      occasion: 'Everyday Dining',
      recommendedFor: ['Casual'],
      review:
        'Vel aliquid incidunt tenetur minima dolores sit asperiores dolor neque. Unde quis at voluptatibus accusantium iusto illo.',
    },
    {
      _id: '67806166',
      date: '2017-12-08T22:05:01.166Z',
      username: 'Anastasia Hintz',
      userReviews: 3,
      foodScore: 4,
      serviceScore: 1,
      ambianceScore: 3,
      valueScore: 5,
      overallScore: 4,
      noiseLevel: 1,
      wouldRecommend: true,
      occasion: 'Business Meal',
      recommendedFor: ['Worth the Drive'],
      review: 'Qui voluptate sit voluptas et quo ut unde.',
    },
  ],
};
