export default {
  _id: '52566848',
  name: 'Handmade Soft Computer',
  reviews: [
    {
      _id: '67806166',
      date: '2018-09-12T12:00:00.000Z',
      username: 'Anastasia Hintz',
      userReviews: 1,
      userLocation: 'San Francisco',
      foodScore: 1,
      serviceScore: 1,
      ambienceScore: 1,
      valueScore: 1,
      overallScore: 1,
      noiseLevel: 1,
      wouldRecommend: true,
      occasion: 'Business Meal',
      recommendedFor: ['Good for Groups'],
      text: 'This is a sample one star review.',
    },
    {
      _id: '34823729',
      date: '2018-09-06T20:00:00.000Z',
      username: 'Shannon Stoltenberg III',
      userReviews: 2,
      userLocation: 'Los Angeles',
      foodScore: 3,
      serviceScore: 3,
      ambienceScore: 3,
      valueScore: 3,
      overallScore: 3,
      noiseLevel: 2,
      wouldRecommend: true,
      occasion: 'Everyday Dining',
      recommendedFor: ['Casual'],
      text:
        'This is a sample three star review. This is a sample three star review. This is a sample three star review.',
    },
    {
      _id: '68730078',
      date: '2018-09-05T20:00:00.000Z',
      username: 'Zander Crona',
      userReviews: 20,
      userLocation: 'New York City',
      foodScore: 5,
      serviceScore: 5,
      ambienceScore: 5,
      valueScore: 5,
      overallScore: 5,
      noiseLevel: 4,
      wouldRecommend: true,
      occasion: 'Business Meal',
      recommendedFor: ['Great Beer'],
      text:
        'This is a sample five star review. This is a sample five star review. This is a sample five star review. This is a sample five star review. This is a sample five star review.',
    },
  ],
};
