export default {
  _id: '52566848',
  name: 'Handmade Soft Computer',
  reviews: [
    {
      _id: '67806166',
      date: '2018-09-12T12:00:00.000Z',
      username: 'Anastasia Hintz',
      userReviews: 3,
      foodScore: 1,
      serviceScore: 1,
      ambianceScore: 1,
      valueScore: 1,
      overallScore: 1,
      noiseLevel: 1,
      wouldRecommend: true,
      occasion: 'Business Meal',
      recommendedFor: ['Worth the Drive'],
      review: 'This is a sample one star review.',
    },
    {
      _id: '34823729',
      date: '2018-09-06T20:00:00.000Z',
      username: 'Shannon Stoltenberg III',
      userReviews: 10,
      foodScore: 3,
      serviceScore: 3,
      ambianceScore: 3,
      valueScore: 3,
      overallScore: 3,
      noiseLevel: 2,
      wouldRecommend: true,
      occasion: 'Everyday Dining',
      recommendedFor: ['Casual'],
      review:
        'Vel aliquid incidunt tenetur minima dolores sit asperiores dolor neque. Unde quis at voluptatibus accusantium iusto illo.',
    },
    {
      _id: '68730078',
      date: '2018-09-05T20:00:00.000Z',
      username: 'Grady Crona',
      userReviews: 20,
      foodScore: 5,
      serviceScore: 5,
      ambianceScore: 5,
      valueScore: 5,
      overallScore: 5,
      noiseLevel: 4,
      wouldRecommend: true,
      occasion: 'Business Meal',
      recommendedFor: ['Great Beer'],
      review:
        'Accusamus in quo et in. Possimus fugit nobis aut. Ullam aut dolorem perspiciatis perspiciatis quia nostrum.',
    },
  ],
};
